---
title: "Validation App Notes"
author: "GLMRosa"
format: pdf
---

# Validation App

### To do now

- Ok do dos warning está apagado
- Verificar se o 'play' default para 'R session' funciona em windows
- Diferenças no output são detectadas como unsaved rows, controlar quando o que acontece é a comparação de um dataset vazio com um cheio
- Fazer um manual de uso da interface
- Fazer um segundo conjunto de dados de demonstração, maior para varificar questões de performance
- Verificar se funciona com o MonitoraSomAlt e formatos relacionados

### Ideias

- Qual é o efeito dos pads de tempo e frequência para a detecção
- Por enquanto o controle de templates é feito inteiramente por meio da tabela de metadados. Verificar como a presença de todos os metadados pode ser usada pelo app de validação. É possível checar se os metadados necessários estão todos contidos no nome do template e atualizar as informações necessárias no server, caso não estejam disponíveis, serão obtidas a partir da tabela de metadados. Isso requer a padronização do método de salvamento dos templates. É necessário decidir quais infos vão no nome do arquivo e quais vão nos metadados do priorio arquivo wav.

### To do later

- Adicionar controle mais preciso sobre a escala de cores, com a quantidade de níveis, possíbilidade de inversão e de interpolação.
- Adicionar seed específica para os diagnósticos
- Adicionar opção para mostrar a sundscape somente na banda em zoom_freq
- Novas opções para o audio reproduzido
  - filtro de banda
  - normalização
- Modificar o sistema para que seja possível haver mais de uma validação por detecção. Append de validações de usuários diferentes?
- Controle para evitar que o path selecionado suma ao clicar adicentalmente no botão de load.
- Um menu de seleção de input de soundscapes para navegar diretamente entre elas ainda não é possível, pois a atualização mutua com o input da ID gera um loop aberto na indexação quando em modo aleatório, ou impede a navgação correta para a detec anterior quando em modo sequencial. Por essa razão input$soundscape_name foi convertido em textInput em modo desabilitado.
- Várias seções do código são duplicadas para possibilitar que sejam acessadas por diferentes tipos de inputs, como hotkeys e actionButtons ao mesmo tempo sem que uma opção disabilite a outra. Verificar uma forma de simplificar isso.
- Na versão mais nova, onde houve a adaptação para o formato de planilha mais completo, na hora de tocar o wav do template, são omitidos os pads de silêncio somente quando está ativo o player em html. É necessário levar os outros players ao mesmo padrão? Talvez seja melhor aderir à ideia de 'play visible', com a exceção de trechos de silêncio.
- Armazenamento dos dados em um banco de dados em SQL


### Log de pedidos



- Fixar largura das colunas das tabelas
  - R: Controlar a largura das colunas é um pouco complexo pq mexe com a renderização da tabela em html, já que não tem argumentos na função para controlar isso de forma mais direta.

- Deixar a interface de selecionar diretórios igual à interface de selecionar arquivos
  - R: Chequei a fundo, não foi possível fazer as funções shinyDirButton() e shinyFilesButton() abrirem o mesmo tipo de janela.
  -
- Adicionar autoplay
  - R: Não deu. Em todos os três métodos de tocar o som a parada trava de alguma forma. No html trava a renderização do player. No "R session" ou " External player" trava todo o processamento da interface até que o som termine de tocar ou seja fechada a janela. Não me lembrava, mas implementei 1 e 2 como atalhos para tocar justamente para não ter que implementar um "autoplay".

- Mostrar a hora absoluta do sonograma da detecção
  - R: Para fazer isso a gente teria que assumir que essa informação está em algum lugar do arquivo, seja no nome ou nos metadados. Fiz o shiny para que ele não dependa de nada do tipo para que os arquivos possam ter qualquer nome e estar qualquer estrutura de pastas. Talvez no futuro possamos implementar a opção de escolher entre diferentes formatos de nomenclatura, como os do audiomoth ou dos SM4, daí a gente consegue colocar um feature como esse.
