---
title: "Segmentation app notes"
author: "GLMRosa"
format: pdf
---

# Segmentation App

### To do now


- Exibir score no sonograma da detecção
- Atualizar os campos de score na UI
- next no F e
- Criar a pasta temp caso não exista
- Corrigir warning de datatable

- Adicionar hotkeys para:
  - Hotkeys para next (F) e prev (R) soundscape
  - Salvar tabela de ROIs
  - Exportar nova tabela de ROIs
  - Exportar sonograma da soundscape
  - Exportar cortes de audio das rois selecionadas
  - Exportar sonogramas das rois selecionadas (mesmo destino dos audios)
- Adicionar referências para os atalhos de teclado nos pop-overs
- Adicionar a lista de espécies disponíveis como variável na tabela de ROIs?

- Ativar mecanismo de detecção de sistema para os players
  - Detectar se o sox está disponível?
  - Pedir caminho para o player quando houver "R session" no windows
  - Apresentar erro de detecção se o sox não estiver disponível no linux ou no mac

- verificar os padrões usados em https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.3329

- Progresso
  - Rever o que é informado na barra de progresso
  - Criar uma tabela a partir da compilação de todas as ROIs disponíveis no diretório


### To do later
- Player focal
  - ROIs selecionadas na tabela são concatenadas e tocadas em sequência
  - Caso não haja nenhuma selecionada, toca a última feita
  - Adicionar checkbox para aplicar filtros de banda nas duas opções acima
- Dar ao usuário a possibilidade de editar o nome da tabela de rois?
- Adicionar botões para a nmavegação entre tabelas de rois?
- Adicionar controle mais preciso sobre a escala de cores, com a quantidade de níveis, possíbilidade de inversão e de interpolação.
- Adicionar um checkbox para escolher se o sonograma será renderizado com a escala de cores invertida
- Escolha entre segmentação com atribuição prévia ou posterior dos metadados de cada roi. No modo de atribuição posterior, inputs são dados em uma pop-up, sendo que o usuário tem a opção de omitir essa pop-up repetindo os metadados atribuídos anteriormente. Isso permitiria um modelo de edição de rois ativas similar à do Raven.
- Plot preenchendo todo o espaço com labels e ticks na parte de dentro do plot. Não foi possível implementar na primeira tentativa porque a captura de input do gráfico renderizado não considera a mudança de margens, resultando na marcação de uma ROI fora da localização desejada.
- Adicionar opções relacionadas a gravações stereo, como a seleção do canal exibido
- bug das Renderização duplicada de sonograma
  - O processamento das ROIs disponíveis acaba depois da renderização, fazendo com que seja feita a renderização uma segunda vez para inclui-las
- Criar funções para que sejam convertidas tabelas de seleção do Raven e Audacity para o formato de output do app
- Fazer uma função para cortar e salvar os cortes de várias tabelas de rois em batch
  - Adicionar opções de filtragem
- Filtros para o salvamento de cortes com labels ou observações específicas na forma de uma caixa de diálogo com match por string
- Adicionar acionamento automático da definição das pastas de output
- Adicionar um sonograma de panorama para navegar no da soundscape
- Usar o file input como alternativa quando o app é usado de forma local, carregando diretamente os múltiplos arquivos que serão segmentados. Talvez seja interessante ter modos remoto e local
https://getbootstrap.com/docs/3.3/components/#glyphicons


```{r}
dput(sort(c(
  "cicadas", "insect at mic", "insect swarm", "vegetation rumble",
  "wind", "rain", "thunder", "water flow", "calibration tune",
  "aircraft", "helicopter", "car/road", "voice notes", "conversation",
  "human voice (other)"
)))
```
