#' Set the workspace for the monitoraSom package
#'
#' @description `r lifecycle::badge("experimental")`
#'
#'   This function sets the working directory to the project path and creates
#'   the necessary directories if they do not exist. It also creates the species
#'   labels file if it doesn't exist.
#'
#' @param project_path The path to the project directory. If NULL, the function
#'   will try to determine the project path automatically based on the path to
#'   the R script that is being executed.
#' @param app_presets_path The path to the app presets directory. This path
#'   contains the species labels file and will be used to store temporary files
#'   generated by the segmentation and validation apps.
#' @param soundscapes_path The path to the soundscapes directory. This path is
#'   destined to store soundscape recordings when those are stored within the
#'   project directory.
#' @param soundscapes_metadata_path The path to the soundscapes metadata
#'   directory.
#' @param recordings_path The path to the recordings directory. This path is
#'   destined to store additional recordings, such as focal recordings, that
#'   from which templates will be extracted.
#' @param roi_tables_path The path to the ROI tables directory.
#' @param roi_cuts_path The path to the ROI cuts directory. Although the format
#'   is the same as the templates files, the ROI cuts should not be stored
#'   unless explicitly selected as such.
#' @param templates_path The path to the templates directory.
#' @param templates_metadata_path The path to the templates metadata directory.
#' @param match_grid_metadata_path The path to the match grid metadata
#'   directory.
#' @param match_scores_path The path to the match scores directory.
#' @param detections_path The path to the detections directory.
#' @param detection_cuts_path The path to store detection cuts produced by
#'   within the validation app.
#' @param detection_spectrograms_path The path to store detection spectrograms
#'   produced by within the validation app.
#' @param validation_outputs_path The path to store validated detection tables.
#' @param validation_diagnostics_path The path to store validation diagnostics.
#' @param example_data Logical indicating whether to populate the workspace with
#'   example data. Defaults to FALSE.
#'
#' @returns Multiple directories at the project path.
#' @export
#' @examples
#' \dontrun{
#'
#' # The script below os intended to be run from the a clean R session within a new
#' # project diorectory. The commands below should not be run in an existing
#' # project. After running the commands below, close the current R session and
#' # start a new one within the project directory to run the examples or to build a
#' # new project from scratch.
#'
#' # set the workspace to the current directory and populate it with the complete
#' # example data. Uncomment the command below to run it.
#'
#' # library(monitoraSom)
#' # set_workspace(
#' #     project_path = NULL, ext_soundscapes_path = FALSE, example_data = TRUE
#' # )
#'
#' # Or, alternatively, set the workspace to the current directory and populate it
#' # only with the subdirectories with the recommended structure for a new project.
#' # When working with soundscapes stored in external directories, which is highly
#' # recommended, the `ext_soundscapes_path` argument should be set to `TRUE` and
#' # it will prevent the creation of a soundscapes subdirectory. Uncomment the
#' # command below to run it.
#'
#' # library(monitoraSom)
#' # set_workspace(
#' #     project_path = NULL, ext_soundscapes_path = TRUE, example_data = FALSE
#' # )
#'
#' }
set_workspace <- function(
    project_path = NULL, example_data = FALSE,
    app_presets_path = "./app_presets/",
    soundscapes_path = "./soundscapes/",
    soundscapes_metadata_path = "./soundscapes_metadata/",
    recordings_path = "./recordings/",
    roi_tables_path = "./roi_tables/",
    roi_cuts_path = "./roi_cuts/",
    templates_path = "./templates/",
    templates_metadata_path = "./templates_metadata/",
    match_grid_metadata_path = "./match_grid_metadata/",
    match_scores_path = "./match_scores/",
    detections_path = "./detections/",
    detection_cuts_path = "./detection_cuts/",
    detection_spectrograms_path = "./detection_spectrograms/",
    validation_outputs_path = "./validation_outputs/",
    validation_diagnostics_path = "./validation_diagnostics/"
    ) {

    # requireNamespace("rstudioapi")
    # requireNamespace("openxlsx")
    # requireNamespace("tuneR")
    # requireNamespace("usethis")

    if (is.null(project_path)) {
        tryCatch(
            {
                project_path <- dirname(
                    rstudioapi::getSourceEditorContext()$path
                )
            },
            error = function(e) {
                stop(
                    "Could not determine project path automatically. ",
                    "Please provide project_path parameter."
                )
            }
        )
    } else {
        # Create project if path exists
        if (dir.exists(project_path)) {
            # check if the project file already exists
            if (length(list.files(project_path, pattern = "*.Rproj")) > 0) {
                warning(
                    "An R project already exists at the provided project path. ",
                    "For replacing the existing project, please delete the ",
                    "existing project and run the function again."
                )
            } else {
                message(
                    "If an answer is required below, the current directory ",
                    "may already be within another R project. ",
                    "Do you want to create it here anyway? (not recommended)"
                )
                suppressMessages(
                    usethis::create_project(
                        path = project_path, open = FALSE, rstudio = TRUE
                    )
                )
                message("Created new R project at: ", project_path)
            }
        } else {
            stop("The provided project path does not exist")
        }
    }

    directories <- list(
        app_presets = app_presets_path,
        soundscapes = soundscapes_path,
        soundscapes_metadata = soundscapes_metadata_path,
        recordings = recordings_path,
        templates = templates_path,
        templates_metadata = templates_metadata_path,
        match_grid_metadata = match_grid_metadata_path,
        roi_tables = roi_tables_path,
        roi_cuts = roi_cuts_path,
        detections = detections_path,
        match_scores = match_scores_path,
        detection_spectrograms = detection_spectrograms_path,
        detection_cuts = detection_cuts_path,
        validation_outputs = validation_outputs_path,
        validation_diagnostics = validation_diagnostics_path
    )

    create_directory <- function(path) {
        if (is.null(path)) {
            stop("There are empty paths in the directories list.")
        }
        if (!is.na(path)) {
            if (!is.character(path)) {
                stop("The path must be a character string or NA.")
            }
            dir_name <- deparse(substitute(path))
            if (!dir.exists(path)) {
                dir.create(path)
                message(
                    "- The '", names(path), "' directory WAS CREATED at '",
                    path, "'"
                )
            } else {
                message(
                    "- The '", names(path), "' directory ALREADY EXISTS at '",
                    path, "'"
                )
            }
        }
    }
    # Use Map instead of lapply to preserve names
    invisible(
        Map(
            function(path, name) {
                create_directory(setNames(path, name))
            },
            directories, names(directories)
        )
    )

    if (file.exists(file.path(project_path, ".gitignore"))) {
        file.remove(file.path(project_path, ".gitignore"))
    }
    if (dir.exists(file.path(project_path, "R"))) {
        unlink(file.path(project_path, "R"), recursive = TRUE)
    }

    if (!is.na(app_presets_path)) {
        labels_file <- file.path(app_presets_path, "sp_labels.xlsx")
        if (!file.exists(labels_file)) {
            data("sp_labels", package = "monitoraSom", envir = environment())
            openxlsx::write.xlsx(sp_labels, labels_file)
        } else {
            message(
                "- The labels file already exists. It will not be overwritten."
            )
        }
    }

    # Attention: exporting data does check if the path exists because it is
    # already checked in the create_directory function.
    if (example_data) {
        if (!is.na(soundscapes_path)) {
            data(ls_soundscapes, package = "monitoraSom", envir = environment())
            ls_soundscapes_files <- file.path(
                soundscapes_path, names(ls_soundscapes)
            )
            if (!all(file.exists(ls_soundscapes_files))) {
                invisible(
                    lapply(1:length(ls_soundscapes), function(i) {
                        tuneR::writeWave(
                            ls_soundscapes[[i]],
                            file.path(soundscapes_path, names(ls_soundscapes)[i])
                        )
                    })
                )
                message(
                    "- The soundscape recordings WERE CREATED at '",
                    soundscapes_path, "'."
                )
            } else {
                message(
                    "- At least one of the soundscape recordings ALREADY EXISTS at '", soundscapes_path, "'. They will not be overwritten."
                )
            }
        }

        if (!is.na(recordings_path)) {
            data(ls_recordings, package = "monitoraSom", envir = environment())
            ls_recordings_files <- file.path(
                recordings_path, names(ls_recordings)
            )
            if (!all(file.exists(ls_recordings_files))) {
                invisible(
                    lapply(1:length(ls_recordings), function(i) {
                        tuneR::writeWave(
                            ls_recordings[[i]],
                            file.path(recordings_path, names(ls_recordings)[i])
                        )
                    })
                )
                message(
                    "- The recordings WERE CREATED at '", recordings_path, "'."
                )
            } else {
                message(
                    "- At least one of the recordings ALREADY EXISTS at '",
                    recordings_path, "'. They will not be overwritten."
                )
            }
        }

        if (!is.na(templates_path)) {
            data(ls_templates, package = "monitoraSom", envir = environment())
            ls_templates_files <- file.path(
                templates_path, names(ls_templates)
            )
            if (!all(file.exists(ls_templates_files))) {
                invisible(
                    lapply(1:length(ls_templates), function(i) {
                    tuneR::writeWave(
                        ls_templates[[i]],
                            file.path(templates_path, names(ls_templates)[i])
                        )
                    })
                )
                message(
                    "- The templates WERE CREATED at '", templates_path, "'."
                )
            } else {
                message(
                    "- At least one of the templates ALREADY EXISTS at '",
                    templates_path, "'. They will not be overwritten."
                )
            }
        }

        if (!is.na(roi_tables_path)) {
            data(ls_roi_tables, package = "monitoraSom", envir = environment())
            ls_roi_tables_files <- file.path(
                roi_tables_path, names(ls_roi_tables)
            )
            if (!all(file.exists(ls_roi_tables_files))) {
                invisible(
                    lapply(1:length(ls_roi_tables), function(i) {
                        write.csv(
                            ls_roi_tables[[i]],
                            file.path(roi_tables_path, names(ls_roi_tables)[i])
                        )
                    })
                )
                message(
                    "- The ROI tables WERE CREATED at '", roi_tables_path, "'."
                )
            } else {
                message(
                    "- At least one of the ROI tables ALREADY EXISTS at '",
                    roi_tables_path, "'. They will not be overwritten."
                )
            }
        }

        if (!is.na(soundscapes_metadata_path)) {
            data(df_soundscapes, package = "monitoraSom", envir = environment())
            soundscapes_file <- file.path(
                soundscapes_metadata_path, "df_soundscapes.csv"
            )
            if (!file.exists(soundscapes_file)) {
                write.csv(df_soundscapes, soundscapes_file)
                message(
                    "- The soundscapes metadata file WAS CREATED at '", soundscapes_metadata_path, "'."
                )
            } else {
                message(
                    "- The soundscapes metadata file ALREADY EXISTS at '", soundscapes_metadata_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(templates_metadata_path)) {
            data(df_templates, package = "monitoraSom", envir = environment())
            templates_file <- file.path(
                templates_metadata_path, "df_templates.csv"
            )
            if (!file.exists(templates_file)) {
                write.csv(df_templates, templates_file)
                message(
                    "- The templates metadata file WAS CREATED at '",
                    templates_metadata_path, "'."
                )
            } else {
                message(
                    "- The templates metadata file ALREADY EXISTS at '", templates_metadata_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(match_grid_metadata_path)) {
            data(df_grid, package = "monitoraSom", envir = environment())
            grid_file <- file.path(match_grid_metadata_path, "df_grid.csv")
            if (!file.exists(grid_file)) {
                write.csv(df_grid, grid_file)
                message(
                    "- The match grid metadata file WAS CREATED at '",
                    match_grid_metadata_path, "'."
                )
            } else {
                message(
                    "- The match grid metadata file ALREADY EXISTS at '", match_grid_metadata_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(detections_path)) {
            data(df_detecs, package = "monitoraSom", envir = environment())
            detections_file <- file.path(detections_path, "df_detecs.csv")
            if (!file.exists(detections_file)) {
                write.csv(df_detecs, detections_file)
                message(
                    "- The detections file WAS CREATED at '", detections_path,
                    "'."
                )
            } else {
                message(
                    "- The detections file ALREADY EXISTS at '",
                    detections_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(match_scores_path)) {
            data(df_scores, package = "monitoraSom", envir = environment())
            match_scores_file <- file.path(match_scores_path, "df_scores.rds")
            if (!file.exists(match_scores_file)) {
                saveRDS(df_scores, match_scores_file)
                message(
                    "- The match scores file WAS CREATED at '",
                    match_scores_path, "'."
                )
            } else {
                message(
                    "- The match scores file ALREADY EXISTS at '",
                    match_scores_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(validation_outputs_path)) {
            data(
                df_detecs_val_manual,
                package = "monitoraSom", envir = environment()
            )
            detections_file <- file.path(
                validation_outputs_path, "df_detecs_val_manual.csv"
            )
            if (!file.exists(detections_file)) {
                write.csv(df_detecs_val_manual, detections_file)
                message(
                    "- The validated detections file WAS CREATED at '",
                    detections_path, "'."
                )
            } else {
                message(
                    "- The detections file ALREADY EXISTS at '",
                    detections_path, "'. It will not be overwritten."
                )
            }
        }

        if (!is.na(validation_outputs_path)) {
            data(
                df_detecs_val_tovlp,
                package = "monitoraSom", envir = environment()
            )
            detections_file <- file.path(
                validation_outputs_path, "df_detecs_val_tovlp.csv"
            )
            if (!file.exists(detections_file)) {
                write.csv(df_detecs_val_tovlp, detections_file)
                message(
                    "- The validated detections file WAS CREATED at '",
                    detections_path, "'."
                )
            } else {
                message(
                    "- The validated detections file ALREADY EXISTS at '",
                    detections_path, "'. It will not be overwritten."
                )
            }
        }
        message(
            paste(
                "Workspace and example data set successfully.",
                "Check the workspace and start another R session within the",
                "project to start using the monitoraSom package."
            )
        )
    } else {
        message(
            paste(
                "Workspace set successfully.",
                "Check the workspace and start another R session within the",
                "project to start using the monitoraSom package."
            )
        )
    }
}


